#!/usr/bin/env python3
"""Setup development environment with proper CSRF configuration."""

import os
from pathlib import Path

def setup_development_environment():
    """Set up environment variables for development."""
    
    env_file = Path(__file__).parent / ".env"
    
    env_vars = {
        'FLASK_ENV': 'development',
        'FLASK_DEBUG': 'True',
        'SECRET_KEY': 'dev-secret-key-change-in-production-' + os.urandom(16).hex(),
        'WTF_CSRF_ENABLED': 'True',
        'WTF_CSRF_TIME_LIMIT': '3600',
        'SESSION_COOKIE_SECURE': 'False',
        'LOG_LEVEL': 'INFO'
    }
    
    # Create or update .env file
    with open(env_file, 'w') as f:
        f.write("# Development Environment Configuration\n")
        f.write("# Generated by setup_environment.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print(f"Environment file created: {env_file}")
    print("Please restart your Flask application to apply changes")

if __name__ == "__main__":
    setup_development_environment()